version: '3'

networks: 
  laravel:

services: 
  web_server: 
    image: nginx
    container_name: nginx_1
    ports: 
      - "8080:80"
    volumes:
      - ../laravel_with_docker:/var/www/html/laravel_with_docker
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel
  php:
    build: 
      context: ./app/
      dockerfile: Dockerfile
    container_name: php_1
    volumes: 
      - ../laravel_with_docker:/var/www/html/laravel_with_docker
    working_dir: /var/www/html/laravel_with_docker
    ports: 
     - "9001:9000"
    networks: 
     - laravel
  mysql:
    image: mysql:5.7
    container_name: mysql_1
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"
    environment: 
      MYSQL_DATABASE: db_1
      MYSQL_USER: thanhlv
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel


